import React from 'react';
import { InvoiceItem } from '../hooks/useInvoiceGenerator';
import { CompanyProfile } from '../../../../types';

interface Props {
  clientName: string;
  clientTIN: string;
  items: InvoiceItem[];
  totals: { subtotal: number; tax: number; grandTotal: number };
  company: CompanyProfile;
}

export const InvoicePreview: React.FC<Props> = ({ clientName, clientTIN, items, totals, company }) => {
  return (
    <div id="invoice-print-area" className="bg-white shadow-lg border border-slate-200 aspect-[1/1.414] p-10 flex flex-col text-sm text-slate-800 relative overflow-hidden">
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-slate-800 pb-6 mb-6">
        <div>
          <h1 className="text-2xl font-black uppercase tracking-widest">{company.name}</h1>
          <p className="text-slate-500 mt-1">{company.address}</p>
          <p className="text-slate-500">TIN: {company.tin}</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold text-blue-600">INVOICE</h2>
          <p className="font-mono text-slate-500">#INV-{Date.now().toString().slice(-6)}</p>
          <p className="text-slate-500">{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Bill To */}
      <div className="mb-8">
        <p className="text-xs font-bold text-slate-400 uppercase">Bill To:</p>
        <p className="font-bold text-lg">{clientName || 'Cash Client'}</p>
        {clientTIN && <p className="text-slate-500">TIN: {clientTIN}</p>}
      </div>

      {/* Table */}
      <table className="w-full text-left mb-auto">
        <thead className="bg-slate-100">
          <tr>
            <th className="p-3 font-bold">Description</th>
            <th className="p-3 text-right">Qty</th>
            <th className="p-3 text-right">Price</th>
            <th className="p-3 text-right">Total</th>
          </tr>
        </thead>
        <tbody>
          {items.map(item => (
            <tr key={item.id} className="border-b border-slate-100">
              <td className="p-3">{item.desc || 'Item'}</td>
              <td className="p-3 text-right">{item.qty}</td>
              <td className="p-3 text-right">{item.price.toLocaleString()}</td>
              <td className="p-3 text-right font-bold">{item.total.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Totals */}
      <div className="flex justify-end mt-6">
        <div className="w-48 space-y-2">
          <div className="flex justify-between"><span>Subtotal:</span> <span className="font-bold">{totals.subtotal.toLocaleString()}</span></div>
          <div className="flex justify-between text-slate-500"><span>VAT (15%):</span> <span>{totals.tax.toLocaleString()}</span></div>
          <div className="flex justify-between text-lg font-black border-t-2 border-slate-800 pt-2">
            <span>Total:</span> <span>{totals.grandTotal.toLocaleString()}</span>
          </div>
        </div>
      </div>
      
      <div className="mt-12 pt-6 border-t border-slate-200 text-center text-xs text-slate-400">
        Generated by Accounting ERP • Valid Document
      </div>
    </div>
  );
};